Repository zimmerman-team/DX, pull requests merged in 2024-09, with the labels that each got.

#12 chore: update client env variables
  .env.example
  Dockerfile
  Dockerfile.staging
  Dockerfile.test
  docker-compose.dev.yml
  docker-compose.staging.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: size/M

#9 feat: DX-1481 - Redis implementation for DX
  .env.example
  docker-compose.dev.yml
  docker-compose.staging.yml
  docker-compose.test.yml
  docker-compose.yml
  scripts/build.sh
  scripts/redeploy.sh
  scripts/start.sh
  scripts/stop.sh
Labels: size/L

#10 Add logging directory to volumes in test, staging and prod
  docker-compose.dev.yml
  docker-compose.staging.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: size/XS
